/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.pravega.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Status extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6721723705923135739L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Status\",\"namespace\":\"io.pravega.avro\",\"fields\":[{\"name\":\"fileId\",\"type\":\"int\"},{\"name\":\"txnId\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Status> ENCODER =
      new BinaryMessageEncoder<Status>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Status> DECODER =
      new BinaryMessageDecoder<Status>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Status> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Status> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Status> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Status>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Status to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Status from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Status instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Status fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public int fileId;
  @Deprecated public java.lang.CharSequence txnId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Status() {}

  /**
   * All-args constructor.
   * @param fileId The new value for fileId
   * @param txnId The new value for txnId
   */
  public Status(java.lang.Integer fileId, java.lang.CharSequence txnId) {
    this.fileId = fileId;
    this.txnId = txnId;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return fileId;
    case 1: return txnId;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: fileId = (java.lang.Integer)value$; break;
    case 1: txnId = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'fileId' field.
   * @return The value of the 'fileId' field.
   */
  public int getFileId() {
    return fileId;
  }


  /**
   * Sets the value of the 'fileId' field.
   * @param value the value to set.
   */
  public void setFileId(int value) {
    this.fileId = value;
  }

  /**
   * Gets the value of the 'txnId' field.
   * @return The value of the 'txnId' field.
   */
  public java.lang.CharSequence getTxnId() {
    return txnId;
  }


  /**
   * Sets the value of the 'txnId' field.
   * @param value the value to set.
   */
  public void setTxnId(java.lang.CharSequence value) {
    this.txnId = value;
  }

  /**
   * Creates a new Status RecordBuilder.
   * @return A new Status RecordBuilder
   */
  public static io.pravega.avro.Status.Builder newBuilder() {
    return new io.pravega.avro.Status.Builder();
  }

  /**
   * Creates a new Status RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Status RecordBuilder
   */
  public static io.pravega.avro.Status.Builder newBuilder(io.pravega.avro.Status.Builder other) {
    if (other == null) {
      return new io.pravega.avro.Status.Builder();
    } else {
      return new io.pravega.avro.Status.Builder(other);
    }
  }

  /**
   * Creates a new Status RecordBuilder by copying an existing Status instance.
   * @param other The existing instance to copy.
   * @return A new Status RecordBuilder
   */
  public static io.pravega.avro.Status.Builder newBuilder(io.pravega.avro.Status other) {
    if (other == null) {
      return new io.pravega.avro.Status.Builder();
    } else {
      return new io.pravega.avro.Status.Builder(other);
    }
  }

  /**
   * RecordBuilder for Status instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Status>
    implements org.apache.avro.data.RecordBuilder<Status> {

    private int fileId;
    private java.lang.CharSequence txnId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.pravega.avro.Status.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.fileId)) {
        this.fileId = data().deepCopy(fields()[0].schema(), other.fileId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.txnId)) {
        this.txnId = data().deepCopy(fields()[1].schema(), other.txnId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Status instance
     * @param other The existing instance to copy.
     */
    private Builder(io.pravega.avro.Status other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.fileId)) {
        this.fileId = data().deepCopy(fields()[0].schema(), other.fileId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.txnId)) {
        this.txnId = data().deepCopy(fields()[1].schema(), other.txnId);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'fileId' field.
      * @return The value.
      */
    public int getFileId() {
      return fileId;
    }


    /**
      * Sets the value of the 'fileId' field.
      * @param value The value of 'fileId'.
      * @return This builder.
      */
    public io.pravega.avro.Status.Builder setFileId(int value) {
      validate(fields()[0], value);
      this.fileId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'fileId' field has been set.
      * @return True if the 'fileId' field has been set, false otherwise.
      */
    public boolean hasFileId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'fileId' field.
      * @return This builder.
      */
    public io.pravega.avro.Status.Builder clearFileId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'txnId' field.
      * @return The value.
      */
    public java.lang.CharSequence getTxnId() {
      return txnId;
    }


    /**
      * Sets the value of the 'txnId' field.
      * @param value The value of 'txnId'.
      * @return This builder.
      */
    public io.pravega.avro.Status.Builder setTxnId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.txnId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'txnId' field has been set.
      * @return True if the 'txnId' field has been set, false otherwise.
      */
    public boolean hasTxnId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'txnId' field.
      * @return This builder.
      */
    public io.pravega.avro.Status.Builder clearTxnId() {
      txnId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Status build() {
      try {
        Status record = new Status();
        record.fileId = fieldSetFlags()[0] ? this.fileId : (java.lang.Integer) defaultValue(fields()[0]);
        record.txnId = fieldSetFlags()[1] ? this.txnId : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Status>
    WRITER$ = (org.apache.avro.io.DatumWriter<Status>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Status>
    READER$ = (org.apache.avro.io.DatumReader<Status>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.fileId);

    out.writeString(this.txnId);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.fileId = in.readInt();

      this.txnId = in.readString(this.txnId instanceof Utf8 ? (Utf8)this.txnId : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.fileId = in.readInt();
          break;

        case 1:
          this.txnId = in.readString(this.txnId instanceof Utf8 ? (Utf8)this.txnId : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










